active_preset: balanced
presets:
  original:
    name: 원래 조합 (리팩토링 전)
    description: 리팩토링 전에 사용하던 All-OpenAI 조합 (기준점)
    roles:
      category:
        provider: openai
        model: gpt-4.1
      search_rewrite:
        provider: openai
        model: gpt-4o
      condense:
        provider: openai
        model: gpt-4.1
      gate:
        provider: openai
        model: gpt-4.1
      function_analyze:
        provider: openai
        model: o3-mini
  budget:
    name: 최저가 조합
    description: 모든 교체 가능 부분을 Gemini Flash로 설정하여 비용 최소화
    roles:
      category:
        provider: gemini
        model: gemini-2.0-flash
      search_rewrite:
        provider: gemini
        model: gemini-2.0-flash
      condense:
        provider: gemini
        model: gemini-2.0-flash
      gate:
        provider: gemini
        model: gemini-2.5-pro
      function_analyze:
        provider: gemini
        model: gemini-2.5-pro
  balanced:
    name: 가성비 조합
    description: 중요 부분(게이트, 요약)은 OpenAI, 경량 작업은 Gemini 사용
    roles:
      category:
        provider: gemini
        model: gemini-2.0-flash
      search_rewrite:
        provider: gemini
        model: gemini-2.0-flash
      condense:
        provider: gemini
        model: gemini-2.0-flash
      gate:
        provider: openai
        model: o3-mini
      function_analyze:
        provider: openai
        model: o3-mini
  premium:
    name: 최고성능 조합
    description: 모든 교체 가능 부분을 OpenAI 프리미엄 모델로 설정하여 품질 극대화
    roles:
      category:
        provider: openai
        model: o3-mini
      search_rewrite:
        provider: openai
        model: gpt-4.1
      condense:
        provider: openai
        model: gpt-4.1
      gate:
        provider: openai
        model: o3-mini
      function_analyze:
        provider: openai
        model: o3-mini
  openai_only:
    name: OpenAI 전용 (경량)
    description: 모든 부분을 OpenAI nano 모델로 설정 (Gemini 미사용)
    roles:
      category:
        provider: openai
        model: gpt-5-nano
      search_rewrite:
        provider: openai
        model: gpt-4.1-nano
      condense:
        provider: openai
        model: gpt-4.1-nano
      gate:
        provider: openai
        model: o3-mini
      function_analyze:
        provider: openai
        model: o3-mini
  gpt4_nano_only:
    name: GPT-4.1 Nano 전용
    description: 모든 교체 가능 부분을 GPT-4.1 Nano로 설정 (극도로 저렴한 OpenAI 전용, Gate만 Gemini)
    roles:
      category:
        provider: openai
        model: gpt-4.1-nano
      search_rewrite:
        provider: openai
        model: gpt-4.1-nano
      condense:
        provider: openai
        model: gpt-4.1-nano
      gate:
        provider: gemini
        model: gemini-2.0-flash
      function_analyze:
        provider: gemini
        model: gemini-2.5-pro
  gpt5_nano_only:
    name: GPT-5 Nano 전용
    description: 모든 교체 가능 부분을 GPT-5 Nano로 설정 (최신 경량 모델)
    roles:
      category:
        provider: openai
        model: gpt-5-nano
      search_rewrite:
        provider: openai
        model: gpt-5-nano
      condense:
        provider: openai
        model: gpt-5-nano
      gate:
        provider: openai
        model: gpt-5-nano
      function_analyze:
        provider: openai
        model: o3-mini
  custom_1:
    name: 사용자 정의 1
    description: 사용자가 직접 설정한 조합 (예시)
    roles:
      category:
        provider: openai
        model: gpt-5-nano
      search_rewrite:
        provider: gemini
        model: gemini-2.0-flash
      condense:
        provider: openai
        model: gpt-4.1-nano
      gate:
        provider: openai
        model: o3-mini
      function_analyze:
        provider: openai
        model: o3-mini
fixed_roles:
  function_calling:
    provider: openai
    model: o3-mini
    reason: OpenAI Responses API의 tool calling 기능 종속
  web_search:
    provider: openai
    model: gpt-4.1
    reason: web_search_preview 기능은 gpt-4.1만 지원
  streaming:
    provider: openai
    model: gpt-4.1
    reason: 스트리밍 응답 파싱 로직이 OpenAI API에 종속
role_descriptions:
  category: 공지 카테고리 분류 (학사공지/비교과공지/장학공지/일반공지/해당없음)
  search_rewrite: 검색어 재작성 (사용자 질문 + 문맥 → 최적화된 검색어)
  condense: RAG 컨텍스트 요약 (긴 문서 → 질문에 맞게 요약)
  gate: RAG 게이트 판정 (규정 질문 여부 판단 + JSON 스키마 출력)
  function_analyze: 함수 선택 추론 (LLM이 함수를 선택한 이유 생성 + JSON 스키마 출력)
  function_calling: 함수 호출 판단 및 실행 (OpenAI 전용)
  web_search: 웹 검색 실행 (OpenAI web_search_preview 전용)
  streaming: 스트리밍 응답 생성 (OpenAI 전용)

provider_config:
  openai:
    message_overhead: 3        # 각 메시지당 구조 오버헤드 (role, content)
    reply_priming_overhead: 3  # 응답 준비용 오버헤드
    name_field_overhead: 1     # name 필드 추가 시 오버헤드
    # 참고: https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb
    
  gemini:
    message_overhead: 0        # Gemini는 메시지 구조 오버헤드 없음
    reply_priming_overhead: 0  # model.count_tokens() API가 실제 토큰 수 제공
    name_field_overhead: 0
