spring:
  application:
    name: halla-univ-chatbot-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    include: secret

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: halla-chatbot${app.mongodb-suffix}

app:
  ai-service-url: ${AI_SERVICE_URL:http://localhost:3000}

  mongodb-suffix: ${MONGODB_SUFFIX:-stg}

  openai-admin-key: ${OPENAI_ADMIN_KEY:}
  openai-project-id: ${OPENAI_PROJECT_ID}
  costs-api-url: ${COSTS_API_URL}
  monthly-llm-usage-limit: ${MONTHLY_COST_LIMIT:1000.0}

  discord-webhook-url: ${DISCORD_WEBHOOK_URL:}
