spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

logging:
  level:
    root: INFO
    com.hallachatbot: INFO

app:
  # 환경변수와 매핑
  mongodb-suffix: ${MONGODB_SUFFIX}
  openai-admin-key: ${OPENAI_ADMIN_KEY}
  openai-project-id: ${OPENAI_PROJECT_ID}
  costs-api-url: ${COSTS_API_URL}
  discord-webhook-url: ${DISCORD_WEBHOOK_URL}
  ai-service-url: ${AI_SERVICE_URL}
  monthly-llm-usage-limit: ${MONTHLY_COST_LIMIT}
