spring:
  data:
    redis:
      cluster:
        nodes: ${REDIS_CLUSTER_NODES}
      ssl:
        enabled: true
  config:
    import: "aws-parameterstore:/chatbot/stg/"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
