spring:
  application:
    name: halla-univ-chatbot-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    include: secret

app:
  # 기본값 설정
  ai-service-url: "http://chatbot-ai-container:8000"
  monthly-llm-usage-limit: 1000.0

  # CORS 설정
  cors:
    allowed-origins:
      - "http://localhost:5173"
      - "https://halla-chatbot.com"
      - "http://localhost:3000"
    allowed-methods: "*"
    allowed-headers: "*"

# 헬스 체크용
management:
  endpoints:
    web:
      exposure:
        include: health, info
