spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

logging:
  level:
    root: INFO
    com.hallachatbot: INFO # 운영 환경은 로그 양 조절

app:
  # config.py의 필드들과 매핑되는 환경변수 설정
  mongodb-suffix: ${MONGODB_SUFFIX}

  openai-admin-key: ${OPENAI_ADMIN_KEY}
  openai-project-id: ${OPENAI_PROJECT_ID}
  costs-api-url: ${COSTS_API_URL}
  discord-webhook-url: ${DISCORD_WEBHOOK_URL}

  # 운영 환경에서는 AI 서비스 컨테이너 이름을 사용 (기본값 사용 시 생략 가능)
  ai-service-url: ${AI_SERVICE_URL:http://chatbot-ai-container:8000}