# LLM API 가격표 (2025년 10월 기준 정정)
# OpenAI + Google Gemini 모델 포함
# 단위: USD per 1M tokens
# 출처: OpenAI 공식 문서 (platform.openai.com), Google Gemini 공식 문서 (ai.google.dev)

models:
  # ===== OpenAI 모델 =====
  - id: gpt-4.1
    provider: openai
    input_per_1m_tokens_usd: 2.00
    output_per_1m_tokens_usd: 8.00
    cache_input_per_1m_tokens_usd: 0.50  # 캐시 입력 75% 할인
    currency: USD
    note: "캐시 입력 시 75% 할인 적용"
    
  - id: o3-mini
    provider: openai
    input_per_1m_tokens_usd: 1.10
    output_per_1m_tokens_usd: 4.40
    cache_input_per_1m_tokens_usd: 0.55
    currency: USD
    note: "캐시 입력 지원"
    
  - id: gpt-4o
    provider: openai
    input_per_1m_tokens_usd: 2.50
    output_per_1m_tokens_usd: 10.00
    cache_input_per_1m_tokens_usd: 1.25
    currency: USD
    note: "Omni 모델, 캐시 입력 지원"
    
  
  # OpenAI nano 모델들 (경량)
  - id: gpt-5-nano
    provider: openai
    input_per_1m_tokens_usd: 0.05
    output_per_1m_tokens_usd: 0.40  # 정정: $0.005 → $0.40
    cache_input_per_1m_tokens_usd: 0.005
    currency: USD
    note: "최신 경량 모델, 캐시 입력 지원"
  
  - id: gpt-4.1-mini
    provider: openai
    input_per_1m_tokens_usd: 0.40
    output_per_1m_tokens_usd: 1.60
    cache_input_per_1m_tokens_usd: 0.10
    currency: USD
    note: "미니 모델, 캐시 입력 지원"
  
  - id: gpt-4.1-nano
    provider: openai
    input_per_1m_tokens_usd: 0.10
    output_per_1m_tokens_usd: 0.40  # 정정: $0.025 → $0.40
    cache_input_per_1m_tokens_usd: 0.025
    currency: USD
    note: "나노 모델, 캐시 입력 지원"
  
  # OpenAI 임베딩 모델
  - id: text-embedding-3-small
    provider: openai
    input_per_1m_tokens_usd: 0.02
    output_per_1m_tokens_usd: 0.0  # 임베딩 모델은 출력 없음
    currency: USD
    note: "임베딩 모델, 출력 없음"
  
  # ===== Google Gemini 모델 =====
  # 출처: Google Gemini API 가격 페이지 (ai.google.dev)
  
  - id: gemini-2.0-flash
    provider: gemini
    input_per_1m_tokens_usd: 0.10  # 정정: $0.075 → $0.10
    output_per_1m_tokens_usd: 0.40  # 정정: $0.030 → $0.40
    cache_per_1m_tokens_usd: 0.025
    currency: USD
    note: "텍스트·이미지·비디오 기준, 오디오 입력은 $0.70/M 토큰"
  
  - id: gemini-2.0-flash-lite
    provider: gemini
    input_per_1m_tokens_usd: 0.075
    output_per_1m_tokens_usd: 0.30
    currency: USD
    note: "라이트 버전"
  
  - id: gemini-2.5-flash
    provider: gemini
    input_per_1m_tokens_usd: 0.30  # 정정: $0.075 → $0.30
    output_per_1m_tokens_usd: 2.50  # 정정: $0.030 → $2.50
    cache_per_1m_tokens_usd: 0.03
    currency: USD
    note: "텍스트·이미지·비디오 기준, 오디오 입력은 $1.00/M 토큰"
  
  - id: gemini-2.5-flash-lite
    provider: gemini
    input_per_1m_tokens_usd: 0.10
    output_per_1m_tokens_usd: 0.40
    currency: USD
    note: "가장 저렴한 Gemini 모델"
  
  - id: gemini-2.5-pro
    provider: gemini
    input_per_1m_tokens_usd: 1.25
    output_per_1m_tokens_usd: 10.00  # 정정: $5.00 → $10.00
    currency: USD
    note: "컨텍스트 ≤200k 토큰 기준, 200k 초과 시 입력 $2.50/출력 $15.00"
  
 
# 폴백 기본값 (미등록 모델)
default:
  provider: unknown
  input_per_1m_tokens_usd: 2.50
  output_per_1m_tokens_usd: 10.00
  currency: USD
