name: frontend-ci

on:
  workflow_call:

jobs:
  docker-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build frontend docker image
        run: docker build -t frontend-build-test ./chatbot/frontend